### ISSUE TITLE
IKEA TRÅDFRI (003.182.92) color temperature cannot be set.

### ISSUE THREAD

**Issue by nikolajsheller** [mozilla-iot/zigbee-adapter#10]
I have purchased the following LED to be able to have warm light during the evening and cool light during the day:
http://www.ikea.com/dk/da/catalog/products/00318292/003.182.92

The LED can be added as a dimmable bulb, and on/off state, as well as dimming, can be controlled from the IoT gateway. This is great :)

The bulb has two sets of LEDs, warm-white and cold-white that should be mixable. This is sadly not controllable yet from the IoT gateway.

**Comment by mrstegeman** [comment]
We have not yet added support for this type of bulb but will be doing so in the near future.

Duplicate of https://github.com/mozilla-iot/gateway/issues/685

**Comment by nikolajsheller** [comment]
Awesome. Looking toward to it bing supported.
