### ISSUE TITLE
Aqara air pressure is reported in wrong units

### ISSUE THREAD

**Issue by tdaede** [mozilla-iot/zigbee-adapter#138]
https://www.aliexpress.com/item/32966216308.html

Temperature and humidity work, but air pressure is labeled by the IoT gateway in kPa, though it is clearly in mmHg.

**Comment by Beejeedeb** [comment]
Probably your issue with the Xiaomi sensor is related to mine, see :
https://github.com/mozilla-iot/zigbee-adapter/issues/137

**Comment by Beejeedeb** [comment]
Hi did the change update fix your problem?

**Comment by tdaede** [comment]
Can confirm fixed by https://github.com/mozilla-iot/zigbee-adapter/commit/2e53e1465c917b5e5fab19669661b7a28a1e5c4f
