### ISSUE TITLE
Xiaomi motion sensors use motion instead of occupied

### ISSUE THREAD

**Issue by Beejeedeb** [mozilla-iot/zigbee-adapter#139]
Change request to change occupied to motion in Zigbee code for Xiaomi motion sensors to get the "motion" and "no motion" icons shown in the thing. Below is the code with the (I think) necessary changes. please check the code, I only tested it for the RTCGQ11LM sensor. Code change is related to https://github.com/mozilla-iot/zigbee-adapter/issues/137.

Not sure if for other ZigBee motion sensors the zb-classifier -> addOccupancySensorProperty should be changed also.

---------------------------------------------------------
zb-xiaomi.js

 'lumi.sensor_motion.aq2': { // RTCGQ11LM
    name: 'motion',
    type: Constants.THING_TYPE_BINARY_SENSOR,
    '@type': ['MotionSensor'],
    powerSource: POWERSOURCE.BATTERY,
    occupancyTimeout: 10, // seconds
    activeEndpoints: {
      1: {
        profileId: PROFILE_ID.ZHA_HEX,
        inputClusters: [
          CLUSTER_ID.GENBASIC_HEX,
          CLUSTER_ID.OCCUPANCY_SENSOR_HEX,
          CLUSTER_ID.ILLUMINANCE_MEASUREMENT_HEX,
        ],
        outputClusters: [],
      },
    },
    properties: {
      occupied: {
        descr: {
          '@type': 'MotionProperty',
          type: 'boolean',
          label: 'Motion',
          description: 'Motion Sensor',
        },
        profileId: PROFILE_ID.ZHA,
        endpoint: 1,
        clusterId: CLUSTER_ID.OCCUPANCY_SENSOR,
        attr: 'occupancy',
        value: false,
        parseValueFromAttr: 'parseOccupiedAttr',
      },
      illuminance: {
        descr: {
          '@type': 'LevelProperty',
          type: 'number',
          label: 'Illuminance',
          unit: 'lux',
          minimum: 0,
          maximum: 2000,
          description: 'Lux Sensor',
          readOnly: true,
        },
        profileId: PROFILE_ID.ZHA,
        endpoint: 1,
        clusterId: CLUSTER_ID.ILLUMINANCE_MEASUREMENT,
        attr: 'measuredValue',
        value: 0,
        parseValueFromAttr: 'parseNumericAttr',
      },
    },
  },

'lumi.sensor_motion': {
    name: 'motion',
    type: Constants.THING_TYPE_BINARY_SENSOR,
    '@type': ['MotionSensor'],
    powerSource: POWERSOURCE.BATTERY,
    occupancyTimeout: 10, // seconds
    activeEndpoints: {
      1: {
        profileId: PROFILE_ID.ZHA_HEX,
        inputClusters: [
          CLUSTER_ID.GENBASIC_HEX,
          CLUSTER_ID.OCCUPANCY_SENSOR_HEX,
        ],
        outputClusters: [],
      },
    },
    properties: {
      occupied: {
        descr: {
          '@type': 'MotionProperty',
          type: 'boolean',
          label: 'Motion',
          description: 'Motion Sensor',
        },
        profileId: PROFILE_ID.ZHA,
        endpoint: 1,
        clusterId: CLUSTER_ID.OCCUPANCY_SENSOR,
        attr: 'occupancy',
        value: false,
        parseValueFromAttr: 'parseOccupiedAttr',
      },
    },
  },

-------------------------------------------
zb-property

  /**
   * @method parseOccupiedAttr
   *
   * Converts the ZCL 'occupied' attribute (a bit field) into the 'occupied'
   * property (a boolean).
   */
  parseOccupiedAttr(attrEntry) {
    const propertyValue = attrEntry.attrData != 0;
    const occupiedStr = (propertyValue ? 'motion' : 'no motion');
    return [propertyValue, `${occupiedStr} (${attrEntry.attrData})`];
  }

**Comment by dhylands** [comment]
Because this isn't an actual PR, I can't tell what you actuallly changed. Creating a pull request is described over here: https://help.github.com/en/articles/creating-a-pull-request

I'll create a PR. I think that the only thing that needs to be changed is that BinarySensor needs to be changed to MotionSensor and BooleanProperty needs to be changed to MotionProperty. I don't think any other changes are required.

For reference, this is what a pull-request looks like: https://github.com/mozilla-iot/zigbee-adapter/pull/140

**Comment by dhylands** [comment]
You can see that actual changes proposed by the PR by clicking on the [Changed motion sensors from BinarySensors to MotionSensors](https://github.com/mozilla-iot/zigbee-adapter/pull/140/commits/bf7b277de7353b64c9ceb0429a57b4fd55e0113d) link or the [bf7b277de](https://github.com/mozilla-iot/zigbee-adapter/pull/140/commits/bf7b277de7353b64c9ceb0429a57b4fd55e0113d) link

**Comment by Beejeedeb** [comment]
oké, sorry, thanks for explaining, will look at how to make a PR,  I can make PR for label which should be Motion.

**Comment by Beejeedeb** [comment]
shouldn't #137 be a PR as well

**Comment by dhylands** [comment]
I created PR https://github.com/mozilla-iot/zigbee-adapter/pull/134 which addressed the issue #137 

Sure - creating a PR to change the labels would be a good first exercise. Make sure that you rebase your repository to pick up the latest changes (i.e. the BinartySensor to MotionSensor PR has already been approved and merged into the main repository)

**Comment by dhylands** [comment]
While you're at it, also edit the package.json file and change the version from 0.7.11 to 0.7.12, then I can release a new zigbee adapter with the changes.

**Comment by dhylands** [comment]
Feel free to ask questions about using git or github, if you run into problems along the way.

**Comment by Beejeedeb** [comment]
I made a Pull Request with several improvements https://github.com/mozilla-iot/zigbee-adapter/pull/141 and a pull request for package.json. https://github.com/mozilla-iot/zigbee-adapter/pull/142

Hope I did it correctly :-)

 Question, I was thinking about the "normal" not Xiaomi Zigbee motion sensors. Will the still be recognized as a binarysensor?

**Comment by dhylands** [comment]
Most of the regular motion sensors will be covered by this:
https://github.com/mozilla-iot/zigbee-adapter/blob/e34ebdc1a4b119e494020095875d7f076d0e6fee/zb-classifier.js#L39-L50
and will be classifed as motion sensors.
