### ISSUE TITLE
No dimming property on dimmable color ikea bulb

### ISSUE THREAD

**Issue by mosterme1003** [mozilla-iot/zigbee-adapter#158]
Hey! Like the title says I got a dimmable colored Ikea bulb working after some pairing trouble. Now the properties that I can see in the UI are on and color but there is no brightness level. Is it just not supported? In my mobile browser I can just choose between 10 colors or so and on another device I can additionally choose a saturation and value level in the color options which seem to do the same thing as a brightness property.

**Comment by mrstegeman** [comment]
See https://github.com/mozilla-iot/gateway/issues/1378
