### ISSUE TITLE
Add support for ZLL

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/zigbee-adapter#17]
Some Osram power plugs work with the Zigbee LL 2.0 protocol. Is this supported?

**Comment by dhylands** [comment]
Currently we only support the ZHA protocol. ZLL is not supported.

**Comment by gerritanne** [comment]
In that case, I would like to request support for ZLL :) It’s this something you have in mind for the roadmap?

**Comment by dhylands** [comment]
I definitely think that its something we would like to do.

**Comment by gerritanne** [comment]
That would be great, as I did not yet come across other smart plug brands who work with Zigbee protocol for European socket models (I’d rather not use an extra adapter to go from UK to European socket)

**Comment by dhylands** [comment]
So far, most of the ZLL based lights also support ZHA. You typically need to factory reset them with the ZLL hub turned off (so that they don't immediately repair with the hub). Then our gateway can pair with it.

**Comment by gerritanne** [comment]
Ok, thx for that info. I think I’ll give the Osram Smart+ power plug a try to see if the gateway will pick it up (I don’t have any hubs)...Will let you know the result...

**Comment by gerritanne** [comment]
I just tested the Osram Smart+ plug, and the gateway detected it straight away. Switching on and off works, however it doesn't retrieve the information for Voltage, Current, Frequency, etc...

![image](https://user-images.githubusercontent.com/36508059/37711510-4aa503b2-2d11-11e8-9aae-bd4dd4dbe448.png)

**Comment by mrstegeman** [comment]
@dhylands Done now?

**Comment by dhylands** [comment]
Yes - the problem with voltage and the other fields not showing properly should be fixed.
