### ISSUE TITLE
Add support for Xiaomi Magic Cube

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/zigbee-adapter#194]
I as able to connect the Xiaomi Magic Cube, but it has no properties. 

In theory the Conbee 2 stick supports it. [Deconz details](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/611).

It has a few [abilities](https://youtu.be/5YtqG1wEnng?t=71):
- push
- shake
- double tap on a surface
- rotate on a surface
- rotate it 90 degrees forward
- rotate is 180 degrees forward

I suspect all of those could be translated into momentary button presses. It [seems](https://community.home-assistant.io/t/aqara-cube/54010/59) "rotate on a surface" also translates to a degree value. So you could change the brightness of a light by rotating the cube. It seems it's also possible to detect [which of the 6 sides is up](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L692).

Trying some movements results in this info in the internal logs:

```
2020-02-10 14:15:26.299 INFO   : zigbee: handleReadRsp: ##### No property found for frame #####
```

Data from the json:

```
    "00158d0002a7003a": {
      "addr64": "00158d0002a7003a",
      "addr16": "de53",
      "activeEndpoints": {
        "1": {
          "profileId": "0104",
          "deviceId": "5f01",
          "deviceVersion": 1,
          "inputClusters": [
            "0000",
            "0003",
            "0019",
            "0012"
          ],
          "outputClusters": [
            "0000",
            "0004",
            "0003",
            "0005",
            "0019",
            "0012"
          ],
          "classifierAttributesPopulated": true
        },
        "2": {
          "profileId": "0104",
          "deviceId": "5f02",
          "deviceVersion": 1,
          "inputClusters": [
            "0003",
            "0012"
          ],
          "outputClusters": [
            "0004",
            "0003",
            "0005",
            "0012"
          ],
          "classifierAttributesPopulated": true
        },
        "3": {
          "profileId": "0104",
          "deviceId": "5f03",
          "deviceVersion": 1,
          "inputClusters": [
            "0003",
            "000c"
          ],
          "outputClusters": [
            "0004",
            "0003",
            "0005",
            "000c"
          ],
          "classifierAttributesPopulated": true
        }
      },
      "properties": {},
      "name": "zb-00158d0002a7003a-thing",
      "type": "thing",
      "@type": [],
      "defaultName": "zb-00158d0002a7003a-thing",
      "extendedTimeout": true,
      "activeEndpointsPopulated": true,
      "nodeInfoEndpointsPopulated": true,
      "modelId": "lumi.sensor_cube.aqgl01",
      "appVersion": 5,
      "powerSource": 0
    }
```

I'm looking into how I can propose some code to add (parts of) it. Be aware I am stabbing in the dark here. Work in progress:

Other implementations
- [Dezonz](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/sensor.h#L34)
- [Zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/commit/624f1ced681a33c40d6b0bd5a4b94d3b100c1355)

Device name:
`lumi.sensor_cube.aqgl01`

manufacturerID: 4151

Battery level: 3015

I suspect some of the required details are in this thread:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/611

**Comment by TobiBu** [comment]
Hi,

I just bought the Aquara Cube as well. I am able to pair it but it only shows up as thing without any properties. So I was wondering if there was any progress on this topic...

**Comment by TobiBu** [comment]
Hi,

I looked a little more into this and if I am not completely mistaken I think part of the capabilities of the cube need to be added in the [zb-classifier.js in line 2016](https://github.com/mozilla-iot/zigbee-adapter/blob/5585c68bc453f87feef3ce107b74406f0afcc34a/zb-classifier.js#L2016) like for the Ikea TRADFRI motion sensor.

However, while you get input and output cluster filled when waiting the cube for me those entries are blank...

I will try to digg deeper into this but I am also very new to this and completely stepping in the dark.

**Comment by tim-hellhake** [comment]
Works for me without any problems:
![image](https://user-images.githubusercontent.com/17127122/87456541-60d71300-c607-11ea-891a-8dabde3413d4.png)
Some properties are missing, though.

**Comment by tim-hellhake** [comment]
Seems like someone already fixed it: https://github.com/mozilla-iot/zigbee-adapter/pull/220

**Comment by flatsiedatsie** [comment]
For me it still doesn't work. The state does sometimes change. It changed from 'slide' to 'wakeup' when I just moved it, and to 'shake' when I shook it vigorously. But rotation angle does not change.

![gateway-zigbee-cube](https://user-images.githubusercontent.com/805405/87773279-3792ce80-c823-11ea-9c75-0e962b90e1c1.png)

**Comment by flatsiedatsie** [comment]
Another idea: it could be fun to create a second virtual rotation property that is clamped between 0 and 100. 

Imagine if the virtual rotation is at 80%.
Then if a new rotation is -30, that virtual rotation would drop to 50%.
Then if the user rotates the cube in the other direction, and the cube sends +80, it would go up too 130, which would be capped at 100.

This would create a virtual dial, e.g. for volume control.

**Comment by flatsiedatsie** [comment]
Is anyone else seeing endless streams of this?

```
2020-07-28 17:40:44.735 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:45.751 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:45.752 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:46.768 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:46.769 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:47.785 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:47.786 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:48.802 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:48.803 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:49.821 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:49.822 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:50.838 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:50.839 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:51.855 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:51.856 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:52.872 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:52.872 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:53.889 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:53.890 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
2020-07-28 17:40:54.906 ERROR  : Error getting value for thingId: zb-00158d0002a7003a property: rotate
2020-07-28 17:40:54.907 ERROR  : getProperty: device: zb-00158d0002a7003a not found.
```

**Comment by mrstegeman** [comment]
@flatsiedatsie That's not from the adapter. Your gateway/UI is trying to retrieve properties for a device which the adapter has not seen/added since the last time it started.

**Comment by flatsiedatsie** [comment]
Yes. But the device is there, and its other property (which cube is up) doesn't cause this. So I guess when it starts, instead of setting this property to zero, it just doesn't get a value. But setting rotation to zero as default when the zigbee addon boots up and sees the cube might not be a bad idea?

**Comment by flatsiedatsie** [comment]
Then again, it might be. It would set the volume of the radio to zero everytime the gateway reboots. Maybe I should just ignore it. But it really fills up the logs.
