### ISSUE TITLE
Tradfri dimmer button works, with one small caveat.

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/zigbee-adapter#195]
The IKEA Tradfri physical on-off button is not officially supported, but in practise it works fine. It even supports the dimming ability, where a long press on the up or down button changes the dimming percentage. 

![tradfri-dimmer-button](https://user-images.githubusercontent.com/805405/74384381-6aa6e100-4df1-11ea-9d46-a2952c0cdb05.png)

Only one small detail is strange.

The capability icon looks like the type of a button that can be toggled. Which is fine, since the IKEA button is of the momentary type, so a software toggle should in theory be ok.

But when you press the capability icon, it never resolves into the new state.

![gateway-read-only-can-be-clicked](https://user-images.githubusercontent.com/805405/74383866-56aeaf80-4df0-11ea-8a95-74bc43911008.gif)

The only binary property of the thing is read-only. So perhaps there's a strange situation of a toggle capability that's linked to a read-only property?

Perhaps with a small fix this device could be officially supported?

**Comment by mrstegeman** [comment]
I've released v0.11.2 of this add-on. Give it a shot and let me know if this issue is fixed!

**Comment by mrstegeman** [comment]
This should be fixed in version 0.11.3 of this add-on.
