### ISSUE TITLE
Conbee II lost connections to all and won't reconnect

### ISSUE THREAD

**Issue by MartinAirN** [mozilla-iot/zigbee-adapter#198]
Hi,

The situation is as follows, first setup was a week ago. Multiple Philips Hue lights used to be connected through a Hue Bridge, decided to use the Conbee II instead.
Initial setup was smooth, 1 by 1 each light and 'button' was disconnected from the Hue bridge and connected to the Mozilla-iot-gateway.

(Running Mozilla Iot Gateway version: 0.11.0 && Zigbee-Adapter version: 0.10.8)

To be sure everything kept working I initiated multiple restarts, as a relocation of the hardware was required.

Yesterday I turned the gateway off, and relocated its hardware. Turned everything on, and checked in an hour later when I noticed that the rules did not turn the lights on.

It seemed the gateway UI did have the lights on on, but clicking on either light had a slow UI response and no real response. Also the 'button's did not give any feedback in the UI.

Things I tried so far to get things back to work:
**Just wait for reconnects:**
1. Factory Reset the 'button's and wait for a reconnect
2. Turn off all lights for longer period of time and wait for a reconnect
3. Disconnect the Conbee II for 10+ seconds, plug it back in and wait for a reconnect

**"Forget" devices in the UI and try to reconnect**
1. Factory Reset the 'button's and discover new things
2. Turn off all lights for longer period of time and discover new things
3. Disconnect the Conbee II for 10+ seconds, plug it back in and discover new things
4. Combination of all 3

**"Forget" devices in the UI, delete the dongleMac.json, restart and try to reconnect**
1. Factory Reset the 'button's and discover new things
2. Turn off all lights for longer period of time and discover new things
3. Disconnect the Conbee II for 10+ seconds, plug it back in, restart and discover new things
4. Combination of all 3

So far I have run out of ideas to try. I have enabled all debug logging at some point. Attached are two log files, one where the dongleMac.json was still present and it knew what devices to look for. A second where the json file was removed and a clean discover was tried. (Both were anonymized mac wise, but have recognizeable replacement names)
[KnownNodes.log](https://github.com/mozilla-iot/zigbee-adapter/files/4385590/KnownNodes.log)
[NoKnownNodes.log](https://github.com/mozilla-iot/zigbee-adapter/files/4385591/NoKnownNodes.log)

To me the thing that wonders me most is the fact that the dongle itself reports rebindRequired:
`Node: 00conbeeII000mac 0000 Name: zb-00conbeeII000mac-Dongle       rebindRequired: true endpoints: []`

**Comment by chasingmaxwell** [comment]
I seem to be having this exact issue. @MartinAirN , did you ever find a solution?

**Comment by chasingmaxwell** [comment]
I updated the firmware on the conbee II and reset my lights and now it is working again.

**Comment by MartinAirN** [comment]
Yes, it was on my backlog to fix this.

My fix was a bit more extensive as @chasingmaxwell 's fix, however that may be due to earlier attempts to fix the issue.

For me the fix was:
1. Forget all devices on the Gateway & remove all files of the zigbee plugin.
2. Use another zigbee device (such as a Hue Bridge) to connect all devices and change their channel.
3. Update the Conbee II firmware.
4. Unlink all devices from the 'bridge'.
5. Connect the Conbee II stick and repair from Mozilla Gateway.
