### ISSUE TITLE
Today's update misclassifies my lights as buttons.

### ISSUE THREAD

**Issue by rkjnsn** [mozilla-iot/zigbee-adapter#209]
I have six Philips EasySmart T8 LED tube lights that I control with a Conbee II USB device.

Prior to today, they were recognized as "zb-*-undefined" ZigBee devices with both "on" and "level" attributes that I was able to control via Rules and via the web UI. (The web UI often didn't update to show their current state, but that's probably a different bug, and rules with the bulbs as outputs all worked correctly.)

Today, my gateway automatically fetched an update for the zigbee-adapter module, updating it to 0.11.2. Since the update, the lights are being recognized as "zb-*-button" devices with a single, read-only "on" property, and I can no longer control them from my gateway.

What information would it be useful for me to grab to get them properly identified and usable, again?

**Comment by mrstegeman** [comment]
This should be fixed in version 0.11.3 of this add-on. Apologies for the interruption!

**Comment by rkjnsn** [comment]
Thanks for the quick fix! Not sure if it's expected, but they still show up as "zb-*-button" in the log messages. I can set them to as lights in the UI again and my rules that control them are also working, so they seem to be working now, regardless.
