### ISSUE TITLE
time condition didn'T trigger

### ISSUE THREAD

**Issue by arist0v** [mozilla-iot/zigbee-adapter#213]
i create rule based on time of the day:

![image](https://user-images.githubusercontent.com/6615040/83016979-d142ba00-9ff0-11ea-86be-7b8bd9b3689b.png)

when i wake up this morning, my daughter speak wasn'T off, i also created other rule on a smart plug but same result the event didn'T trigger.

i look at the log and i didn't get any log entry about it, did i did something wrong or is there an issue?

**Comment by mrstegeman** [comment]
In the gateway’s localization settings, make sure you have your time zone configured properly.

**Comment by arist0v** [comment]
yes it was, i just double checked to be sure so the timezone isn't the issue!

**Comment by mrstegeman** [comment]
Maybe a good test would be the following:
1. Install the "Virtual Things" add-on
2. Add the "Virtual On/Off Switch" device to your gateway
3. Set up a rule for a couple minutes in the future to turn the virtual switch on
4. Go back to your things screen and see if it actually turns on

**Comment by arist0v** [comment]
so i try with virtual things, evertyhing work fin, i retry with my tplink/kasa switch, work fine now.... i don'T understand what happen yesterday
