### ISSUE TITLE
Memory looping in Learning Mode

### ISSUE THREAD

**Issue by Mubeen5946** [mozilla-iot/zigbee-adapter#215]
![Capture](https://user-images.githubusercontent.com/54528145/83397649-04c97e00-a40f-11ea-9fe8-5b468a82f1b9.JPG)
 am getting memory looped devices in learning mode while trying to add some ZigBee devices to Pi, using ConBee II Dongle.

Dongle Details:
FCC -ID XVV-CONBEE2
IC 8720A-CONBEE2

Device:
IKEA TRADFRI LED 806 lm E27

Even If the device is switched off, it is detected in the learning mode. It may be looped into some memory register. If I add the looped device, It is not responding.

**Comment by mrstegeman** [comment]
It will stay in that state until it is added to your gateway. There are several other open issues about this device not functioning, though.

**Comment by Mubeen5946** [comment]
I tried adding it, Not syncing or responding properly
