### ISSUE TITLE
Support for non-XBee Zigbee dongles

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/zigbee-adapter#40]
On Twitter @asciidisco [expressed](https://twitter.com/asciidisco/status/1001068346996088832) an interest in implementing support for non-XBee Zigbee dongles and more Zigbee clusters.

I suggest discussing with @dhylands. Could be a separate adapter, or an enhancement/refactoring of the current adapter. I know Dave has also previously expressed an interest in re-writing some adapters in Rust!

See also: mozilla-iot/gateway#1042

**Comment by rahul-thakoor** [comment]
Hello!
I am interested in having an adapter for the Dresden Raspbee.
I would also be interested in helping write one in rust!

**Comment by madmurl0c** [comment]
I'm currently using the Raspbee adapter from Dresden elektronik with their provided software but I'd love to switch over to mozilla iot too. Please consider supporting this device because it's one of the only ones you can easily get your hands on in germany.

**Comment by flatsiedatsie** [comment]
As an aside,  recently a very popular way of connecting to Zigbee amongst the DIY IOT crowd is the [Zigbee2MQTT](https://duckduckgo.com/?q=zigbee2mqtt&t=ffab&ia=software) project.

**Comment by RaulOlmedoCheca** [comment]
I just bought a CC2531. I'd love to see support for this dongle. Any place I should start with to try and implement it on my own?

**Comment by RaulOlmedoCheca** [comment]
I think so, but I haven't tested it, I have very little knowledge about drivers and cc2531 usage

**Comment by mrstegeman** [comment]
I'm going to close this now, since we support multiple dongles. Please open issues and/or PRs for individual dongle support.
