### ISSUE TITLE
SmartThings multipurpose (door) and motion sensors both look like door sensors

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/zigbee-adapter#53]
The two sensors work. The motion sensor triggers and stays "active" (in this case "open") for about 10 seconds even after being put in a closed box. The door sensor immediately changes state between open and closed, based on the position of the magnet. But the GUI reports them both as door sensors.
<img width="629" alt="door-and-motion" src="https://user-images.githubusercontent.com/9487286/45826707-cecf7f00-bca9-11e8-974d-640d03ea7804.png">

**Comment by dhylands** [comment]
This should be fixed by 46c8bac87488d33a779170450fc5cdf18331a9c9
