### ISSUE TITLE
Custom Clusters and Devices

### ISSUE THREAD

**Issue by asadislam94** [mozilla-iot/zigbee-adapter#68]
Hi,
Is it possible to do custom clusters and devices on this? And how would one go about doing it?

Thanks,

**Comment by dhylands** [comment]
Code needs to be added for each particular cluster. The amount of code depends on the behaviour of the cluster.

The zb-classifier.js file is the code which looks at the clusters and creates appropriate properties. This code also depends on the cluster definitions which come from the zcl-id module (on npm). When creating properties, functions from zb-property.js are referred to for translating attribute values to/from property values.

**Comment by asadislam94** [comment]
Thanks.
