### ISSUE TITLE
Hue Dimmer Switch

### ISSUE THREAD

**Issue by who93** [mozilla-iot/zigbee-adapter#69]
Hi,
I guess the Hue Dimmer Switch is not working properly, because it is not listed in the supported device page?

I managed to pair it and the gateway recognizes, if the "On" button is pressed and reports "1-pressed". However, the "Off" button and the two dimmer buttons are not recognized. Have you planned to support the dimmer switch?

Is it possible to add more advanced rules? E.g.: "1-pressed" and "Light"=on, turn off "Light" and "1-pressed" and "Light"=off, turn on "Light"? My goal is to toggle the light with the "On" button of the dimmer.

Thanks!

**Comment by dhylands** [comment]
I ordered a hue dimmer and should get it this week.

**Comment by dhylands** [comment]
The latest version of the zigbee adapter (0.6.5) now supports the Hue Dimmer Switch. There is an on/off property, and a level property. It also generates an event for each button. They're mapped as follows:

* 1-pressed - On button pressed
* 2-pressed - Off button pressed
* 3-pressed - Increase Brightness button pressed
* 4-pressed - Decrease Brightness button pressed
