### ISSUE TITLE
Philips Hue Struana bathroom light detected as unknown device type

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/zigbee-adapter#8]
Originally from: https://github.com/mozilla-iot/gateway/issues/673

I’ve setup the gateway with the RPi 3 and have factory reset my Philips Hue Bathroom light with the Hue Dimmer switch. The gateway then found the Hue but adds it as an unknown device type. So I know see it in the gateway but I cannot do anything (tapping the device in the UI doesn’t do anything).

Any thought why this would not work?

**Comment by dhylands** [comment]
Try removing the bulb from the UI, then remove the zigbee adapter and re-add it. This will update the zigbee adapter. The version installed with the gateway didn't have support for zigbee bulbs.

**Comment by gerritanne** [comment]
Once the bulb is added (saved) as an unknown device type, there is no way to delete it via the UI apart from fulltime reflashing the sdcard and start from scratch. Please let me know of there is an easier way to delete things from the UI.

Even after removing and reinstalling the zigbee adapter, the gateway stil recognises the tradfri as unknown device type.

**Comment by dhylands** [comment]
You can right click on the bulb and select Remove (the only option available)

**Comment by dhylands** [comment]
See this comment: https://github.com/mozilla-iot/zigbee-adapter/issues/9#issuecomment-366314680

**Comment by mrstegeman** [comment]
@gerritanne Did you get this light working as well?

**Comment by gerritanne** [comment]
Yes, this one works as well now...

One comment regarding removal of devices in UI; for iPhone 6/ iPad right clicking is not possible. The suggested “long click”, or holding the button longer, does not bring up the removal button either. Would be nice to make this possible on safari for iPhone iPad as well.

**Comment by mrstegeman** [comment]
Ok, we can look into that issue separately. Thanks for the bug reports!
