### ISSUE TITLE
IKEA Tradfri bulb detected as unknown device type

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/zigbee-adapter#9]
Originally from: https://github.com/mozilla-iot/gateway/issues/679

After reinstalling the gateway and again resetting the tradfri to factory settings, the gateway now finds 'a zigbee' thing, but it's an unknown device type, with a '?' as icon. When I try to connect my Philips Hue Struana bathroom light, I have the exact same thing, the gateway also detects it, but as an unknown device type. When I then save the device in the gateway, I cannot do anything with it. Tapping the thing doesn't do anything, no option to switch on / off neither the option to set the level...

**Comment by dhylands** [comment]
Make sure that you remove and reinstall the zogbee adapter. The zigbee adapter that was released with the gateway didn't have support for the Zigbee bulbs. It was updated a few days after the release.

**Comment by gerritanne** [comment]
After  removing and reinstalling the zigbee adapter, the gateway stil recognises the tradfri as an unknown device type.

**Comment by dhylands** [comment]
Did you also remove and re-add the bulb from the UI?

**Comment by dhylands** [comment]
I went back and reinstalled the 0.3.0 release and I can reproduce the problem (the bulb shows up as a thing and not a bulb).

**Comment by dhylands** [comment]
There is a caching issue in the UI.
- Remove the bulb (right click on the bulb and choose remove)
- Remove the zigbee adapter.
- Do a hard refresh: see https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WocuEYBG3mE
- Add the zigbee-adapter back - this should install the new version.
- Re-add the bulb

You can confirm which version of the adapter is installed by logging on the gateway (https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi) and executing the following command:
```
grep version /home/pi/mozilla-iot/gateway/build/addons/zigbee-adapter/package.json
```
The updated zigbee adapter should show verion 0.3.1 The 0.3.0-pre2 version is the version installed with the gateway.

**Comment by mrstegeman** [comment]
Glad you got it all working! I believe you can do a "right-click" on the iPhone/iPad by long pressing instead.

Here are some issues you can follow for the other things you brought up:
* Reboot button: https://github.com/mozilla-iot/gateway/issues/217
* Change color temperature: https://github.com/mozilla-iot/gateway/issues/685
