### ISSUE TITLE
IKEA dimmable bulb not classified as Light

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/zigbee-adapter#91]
An IKEA dimmable bulb I previously added as a Light is now showing as a MultiLevelSwitch, it doesn't have the Light `@type` available. Did something change in the classifier?

![screen shot 2019-01-22 at 12 51 46](https://user-images.githubusercontent.com/552417/51537096-7cfc5880-1e45-11e9-9002-2859f9cc962a.png)

**Comment by hobinjk** [comment]
Could you share its thing description? Adding it as a Light should have set it permanently as a light. There may be something going on with the adapter

**Comment by mrstegeman** [comment]
@hobinjk Even if it was previously added as a light, if it no longer has that capability reported, it won't be displayed as such.

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/gateway/blob/master/src/models/thing.js#L594-L598

**Comment by dhylands** [comment]
I was able to reproduce this.

2 out of the 3 different IKEA bulbs I have we categorized properly as bulbs. The one that's only dimmable was categorized as a switch.
