### ISSUE TITLE
Failed to start Zigbee add-on: ReferenceError: extraInfo is not defined

### ISSUE THREAD

**Issue by pgupta408** [mozilla-iot/zigbee-adapter#95]
Hi,

While enabling Zigbee Add-on plug-in, I am getting this error:

Failed to start Zigbee add-on: ReferenceError: extraInfo is not defined

How can we fix this problem? 

Thanks

**Comment by dhylands** [comment]
It would be really good to get the complete error message which includes the source file and line number.

**Comment by pgupta408** [comment]
Here it is....

2019-02-06 00:29:54.717 ERROR  : zigbee: Failed to load zigbee-adapter - ReferenceError: extraInfo is not defined
2019-02-06 00:29:54.719 ERROR  : zigbee:     at SerialPort.list.then (/home/pi/.mozilla-iot/addons/zigbee-adapter/node_modules/serial-prober/serial-prober.js:202:44)
2019-02-06 00:29:54.721 ERROR  : zigbee:     at <anonymous>
2019-02-06 00:29:54.723 ERROR  : zigbee:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-02-06 00:29:55.131 INFO   : Plugin: zigbee-adapter died, code = 100 NOT restarting...

**Comment by pgupta408** [comment]
See below for dmesg output. What is the problem????

pi@gateway:~/mozilla-iot $ dmesg | grep USB
[    0.586329] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.591078] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.592251] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.597195] hub 1-0:1.0: USB hub found
[    0.625297] usbhid: USB HID core driver
[    2.030852] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.291052] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.299208] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.308189] hub 1-1:1.0: USB hub found
[    2.630857] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.761022] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.769422] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.892898] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:e4:88:89
[    3.010926] usb 1-1.4: new full-speed USB device number 4 using dwc_otg
[    3.167942] usb 1-1.4: New USB device found, idVendor=10c4, idProduct=8a2a
[    3.176372] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[    4.713438] usbserial: USB Serial support registered for generic
[    4.741211] usbserial: USB Serial support registered for cp210x
[    4.748221] usb 1-1.4: cp210x converter now attached to ttyUSB0
[    4.754941] usb 1-1.4: cp210x converter now attached to ttyUSB1
pi@gateway:~/mozilla-iot $

**Comment by rweise** [comment]
Ich habe übrigens das gleiche Problem auf einer Raspberry Pi Zero W
liegt es vielleicht an der ARMv6 Hardware?

**Comment by dhylands** [comment]
The adapter is failing to find a zigbee dongle. It's supposed to list the USB devices that it did find, but it turns out that there is a bug in that code path. I'll get that fixed. Thanks for the bug report.

**Comment by pgupta408** [comment]
I will try to fix it myself if you give me some detail of code path issue instead of me trying to reverse engineer. 

Thanks

On Feb 7, 2019, at 8:58 AM, Dave Hylands <notifications@github.com> wrote:

The adapter is failing to find a zigbee dongle. It's supposed to list the USB devices that it did find, but it turns out that there is a bug in that code path. I'll get that fixed. Thanks for the bug report.

**Comment by dhylands** [comment]
This should now be fixed in the 0.7.3 release of the zigbee adapter.
